# Generated by Django 5.1.2 on 2025-02-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Уникальный ключ'),
        ),
    ]
