# Generated by Django 5.1.2 on 2025-04-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_board_updated_at'),
        ('column', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='board.board', verbose_name='Доска'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('board', 'name')},
        ),
    ]
