# Generated by Django 5.1.2 on 2025-04-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0002_column_board_alter_column_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
