# Generated by Django 5.1.2 on 2025-04-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_is_sprint_alter_board_created_at_and_more'),
        ('column', '0003_column_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order'], 'verbose_name': 'Колонка', 'verbose_name_plural': 'Колонки'},
        ),
        migrations.AddField(
            model_name='column',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='board.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
