# Generated by Django 5.1.2 on 2025-04-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_board_updated_at'),
        ('project', '0003_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_sprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='project.project'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('project', 'name')},
        ),
    ]
