# Generated by Django 5.1.2 on 2025-05-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_is_sprint_alter_board_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='icon',
            field=models.CharField(default='material-icon-theme:dart', max_length=255),
        ),
    ]
