# Generated by Django 5.1.2 on 2025-05-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='icon',
            field=models.CharField(default='fxemoji:rocket', max_length=255),
        ),
    ]
