# Generated by Django 5.1.2 on 2025-04-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0001_initial'),
        ('project', '0003_project_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['order'], 'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='priority',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='priority',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='priority',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='project.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priority',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='priority',
            unique_together={('project', 'name')},
        ),
    ]
