# Generated by Django 5.1.2 on 2025-05-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0002_alter_priority_options_priority_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='description',
        ),
    ]
