# Generated by Django 5.1.2 on 2025-05-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_tag_color_tag_is_default_tag_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
