# Generated by Django 5.1.2 on 2025-04-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column', '0002_column_board_alter_column_name_and_more'),
        ('task', '0003_task_time_subtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='column.column', verbose_name='Колонка'),
        ),
    ]
