# Generated by Django 5.1.2 on 2025-04-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_remove_task_board_alter_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
