# Generated by Django 5.1.2 on 2025-04-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_options_alter_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_timer_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
