# Generated by Django 5.1.2 on 2025-05-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_is_timer_running_task_timer_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.RemoveField(
            model_name='task',
            name='role',
        ),
    ]
